// export { WaffleTee } from './waffle-tee.png'
// export { HenleyTee } from './striped-henley-baby-tee.png'
// export { TomgirlJean } from './stretch-tomgirl-jean.png'
// export { PuffMiniDress } from './puff-sleeve-mini-dress.png'
// export { SoftShirt } from './oversized-soft-shirt.png'
export { ReactComponent as PeopleTalking } from './people-talking.svg'
export { ReactComponent as ElizaPP } from './eliza.svg'
export { ReactComponent as JuanPP } from './juan.svg'
export { ReactComponent as AlexisPP } from './alexis.svg'
